"""Elimina columnas innecesarias de la tabla Cola

Revision ID: 46fdb3737e78
Revises: 85e1c9dc4128
Create Date: 2023-09-29 17:51:28.239056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "46fdb3737e78"
down_revision = "85e1c9dc4128"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cola", schema=None) as batch_op:
        batch_op.add_column(sa.Column("num_generaciones", sa.Integer(), nullable=False))
        batch_op.drop_column("estado")
        batch_op.drop_column("proceso_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cola", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("proceso_id", mysql.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("estado", mysql.VARCHAR(length=100), nullable=False)
        )
        batch_op.drop_column("num_generaciones")

    # ### end Alembic commands ###
