"""En la cola fecha y proceso como null

Revision ID: 85e1c9dc4128
Revises: 9c1d308dbc39
Create Date: 2023-09-19 19:33:51.736720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "85e1c9dc4128"
down_revision = "9c1d308dbc39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cola", schema=None) as batch_op:
        batch_op.alter_column(
            "ultima_actualizacion",
            existing_type=mysql.BIGINT(display_width=20),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cola", schema=None) as batch_op:
        batch_op.alter_column(
            "ultima_actualizacion",
            existing_type=mysql.BIGINT(display_width=20),
            nullable=False,
        )

    # ### end Alembic commands ###
