"""Cambia la iteracion de generaciones a no ser el primary key

Revision ID: 9c1d308dbc39
Revises: 
Create Date: 2023-09-13 18:39:00.935297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9c1d308dbc39"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generaciones", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.alter_column(
            "iteracion", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generaciones", schema=None) as batch_op:
        batch_op.alter_column(
            "iteracion", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )
        batch_op.drop_column("id")

    # ### end Alembic commands ###
